version: "3.9"
   
services:
  pgsql-db:
    image: postgres
    ports: 
      - "5423:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mysql-db:
    image: mysql
    ports:
      - "3323:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345